[package]
name = "art"
version = "1.0.0"
edition = "2024"
authors = ["Tyler Neely <tylerneely@gmail.com>"]
description = "adaptive radix trie"
license = "MIT OR Apache-2.0"
repository = "https://github.com/spacejam/art"
documentation = "https://docs.rs/art/"

[profile.release]
debug = true
